#!/usr/bin/env python3
"""Validate/generate Mathlab's anti-rediscovery research decision registry.

This registry is an indexed research decision, not an automated theorem
checker, a source DOI verifier or proof of an exhaustive world literature
search. Only the cited source-specific audits carry individual authority.
"""
from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "docs/research/KNOWN-AND-STOPPED-RESEARCH.json"
VIEW = ROOT / "docs/research/KNOWN-AND-STOPPED-RESEARCH.md"
STATUSES = (
    "CLOSED_PROVED", "PRIOR_ART", "STOP_PRODUCT", "SUPERSEDED",
    "MODEL_MISMATCH", "DEFER",
)
EXPECTED_IDS = tuple(f"KR-{i:03d}" for i in range(1, 34))


def validate(record: dict) -> list[dict]:
    if not isinstance(record, dict) or set(record) != {
        "schema", "as_of", "purpose", "policy", "entries"
    }:
        raise ValueError("bad root registry object/schema")
    if record["schema"] != "mathlab.known-and-stopped-research.v1":
        raise ValueError("unsupported anti-rediscovery schema")
    if record["as_of"] != "2026-10-08":
        raise ValueError("missing frozen audit date")
    if not isinstance(record["purpose"], str) or "NOT a global" not in record["purpose"]:
        raise ValueError("must explicitly disclaim global completeness")
    if not isinstance(record["policy"], dict) or set(record["policy"]) != set(STATUSES):
        raise ValueError("disposition vocabulary/policy drift")
    for k, desc in record["policy"].items():
        if not isinstance(desc, str) or len(desc) < 30:
            raise ValueError(f"invalid disposition policy: {k}")
    entries = record["entries"]
    if not isinstance(entries, list) or tuple(x.get("id") for x in entries) != EXPECTED_IDS:
        raise ValueError("missing/duplicate/out-of-order frozen research record")
    seen_titles = set()
    for i, item in enumerate(entries):
        if not isinstance(item, dict) or set(item) != {
            "id", "area", "disposition", "title", "scope",
            "do_not_repeat", "authority", "reopen_only_if", "primary_sources"
        }:
            raise ValueError(f"malformed entry {i}")
        if item["disposition"] not in STATUSES:
            raise ValueError("unknown disposition")
        for fld in ("area", "title", "scope", "do_not_repeat", "reopen_only_if"):
            if not isinstance(item[fld], str) or len(item[fld]) < 10:
                raise ValueError(f"empty {fld} for {item['id']}")
            if "|" in item[fld] or "\n" in item[fld]:
                raise ValueError(f"unsupported Markdown delimiter {fld}")
        if item["title"] in seen_titles:
            raise ValueError("duplicate title")
        seen_titles.add(item["title"])
        authorities = item["authority"]
        if not isinstance(authorities, list) or not authorities:
            raise ValueError("every decision requires a repo source")
        for path in authorities:
            if not isinstance(path, str) or not path.startswith("docs/research/"):
                raise ValueError(f"invalid authority source path: {path}")
            p = (ROOT / path).resolve()
            if ROOT not in p.parents or not p.is_file():
                raise ValueError(f"missing authority path: {path}")
        sources = item["primary_sources"]
        if not isinstance(sources, list):
            raise ValueError("primary_sources must be a list")
        for url in sources:
            if not isinstance(url, str):
                raise ValueError("source link must be string")
            parsed = urlparse(url)
            if parsed.scheme != "https" or not parsed.netloc or "|" in url:
                raise ValueError(f"bad external primary source: {url}")
        if item["disposition"] == "DEFER" and not item["reopen_only_if"]:
            raise ValueError("a deferred track must specify its reopener")
    return entries


def render(record: dict) -> str:
    entries = validate(record)
    lines = [
        "# Известные, доказанные и остановленные исследования Mathlab",
        "",
        "<!-- GENERATED by research/known_registry.py from KNOWN-AND-STOPPED-RESEARCH.json. -->",
        "",
        f"Срез: **{record['as_of']}**. Всего: **{len(entries)}**. "
        "Это **не** утверждение о полноте мировой литературы и не "
        "сертификат проверки доказательств первоисточников.",
        "",
        "Этот реестр нужен, чтобы новый ИИ или исследователь не начинал с нуля "
        "уже закрытую задачу и не объявлял известную идею новой. "
        "Статус всегда ограничен указанной моделью. "
        "DEFER не означает математическую невозможность; "
        "PRIOR_ART не означает полного совпадения моделей; "
        "STOP_PRODUCT не запрещает иной продукт при новом workload.",
        "",
        "## Порядок использования",
        "",
        "Перед созданием новой гипотезы или issue найдите соответствующую "
        "запись, прочитайте её первичное обоснование и ближайший источник. "
        "Переоткрытие допустимо лишь после выполнения указанного "
        "условия reopen_only_if; расхождение модели, ресурсов или гарантий "
        "должно быть записано явно. Численные конечные доказательства "
        "не являются свидетельствами оригинальности общей теоремы.",
        "",
        "Внешние источники — ссылки для проверки вручную, CI не скачивает "
        "статьи и не подтверждает их теоремы.",
        "",
    ]
    for status in STATUSES:
        group = [e for e in entries if e["disposition"] == status]
        lines += [
            f"## {status} ({len(group)})",
            "",
            record["policy"][status],
            "",
            "| ID · область | Известный результат / граница | Почему не повторять | Когда переоткрывать / источники |",
            "| --- | --- | --- | --- |",
        ]
        for e in group:
            authority = ", ".join(
                f"[{Path(a).name}]({a.removeprefix('docs/research/')})"
                for a in e["authority"]
            )
            primary = ", ".join(
                f"[primary {i}]({url})"
                for i, url in enumerate(e["primary_sources"], start=1)
            )
            last = e["reopen_only_if"] + ". **Внутренние:** " + authority
            if primary:
                last += ". **Первоисточники:** " + primary
            lines.append(
                f"| **{e['id']}** · {e['area']} | **{e['title']}**. "
                f"{e['scope']} | {e['do_not_repeat']} | {last} |"
            )
        lines.append("")
    lines += [
        "## Где брать актуальные открытые задачи",
        "",
        "- [OPEN-QUESTIONS.md](OPEN-QUESTIONS.md) — исторические и оставшиеся "
        "вопросы, применять только с учётом статусов здесь.",
        "- [THEOREM-GAP-004](THEOREM-GAP-004-FOUR-STAGE-AUDIT.md) — "
        "предшествующие научные результаты и ограничения переноса.",
        "- [DECISIONS.md](DECISIONS.md) — оригинальные решения и мотивация.",
        "- [CURRENT_STATE](../CURRENT_STATE.md) — текущая ветка, доказательства, CI.",
        "",
        "**Операционный вывод:** ни одна запись в этом реестре сама по себе "
        "не разрешает публикационный claim, Rust crate или новое направление "
        "без исследования конкретного model/product gap.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    if args.check == args.write:
        parser.error("pass exactly one of --check or --write")
    record = json.loads(REGISTRY.read_text(encoding="utf-8"))
    expected = render(record)
    if args.write:
        VIEW.write_text(expected, encoding="utf-8")
    elif not VIEW.is_file() or VIEW.read_text(encoding="utf-8") != expected:
        raise SystemExit("KNOWN_REGISTRY_GENERATED_VIEW_STALE: run --write")
    print("KNOWN_REGISTRY_SCHEMA_PASS", len(record["entries"]))
    print("KNOWN_REGISTRY_AUTHORITY_PATHS_PASS")
    print("KNOWN_REGISTRY_GENERATED_VIEW_PASS")
    print("KNOWN_REGISTRY_DISPOSITIONS", dict(sorted(Counter(
        e["disposition"] for e in record["entries"]
    ).items())))


if __name__ == "__main__":
    main()
